apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
{{ toYaml .Values.kafka.listeners | indent 6  }}
    authorization:
      type: simple
    config:
{{ toYaml .Values.kafka.config | indent 6 }}
    resources:
{{ toYaml .Values.kafka.resources | indent 6 }}
    storage:
{{ toYaml .Values.kafka.storage | indent 6 }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
{{ toYaml .Values.zookeeper.storage | indent 6 }}
    resources:
{{ toYaml .Values.zookeeper.resources | indent 6 }}
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    {{- if .Values.topicOperator.enabled }}
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 256Mi
          cpu: "100m"
        limits:
          memory: 512Mi
          cpu: "1"
    {{- end }}
    {{- if .Values.userOperator.enabled }}
    userOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 256Mi
          cpu: "100m"
        limits:
          memory: 512Mi
          cpu: "1"
    {{- end }}