clusterName: demo-cluster
kafka:
  version: 3.6.0
  replicas: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    - name: external
      port: 9094
      type: loadbalancer
      tls: true
      authentication:
        type: scram-sha-512
  authentication:
    enabled: false
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    default.replication.factor: 3
    min.insync.replicas: 2
    inter.broker.protocol.version: "3.6"
  resources:
    limits:
      memory: 1.5Gi
      cpu: 1
    requests:
      memory: 1Gi
      cpu: 500m
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
zookeeper:
  replicas: 3
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
  resources:
    limits:
      memory: 1.5Gi
      cpu: 1
    requests:
      memory: 1Gi
      cpu: 500m
cruiseControl:
  enabled: true
topicOperator:
  enabled: true
userOperator:
  enabled: true
users:
  user:
    enabled: true
  groupName: myapp-group
  topicName: kgl.dev.myapp
  userAuthentication:
    enabled: true
  userAuthorization:
    enabled: true
  consumerDescribeReadOperation:
    enabled: true
  consumerGroupReadOperation:
    enabled: true
  producerDescribeWriteOperation:
    enabled: true
  producerCreateOperation:
    enabled: false
topics:
  orders:
    enabled: true
    name: kgl.dev.myapp.orders
    spec:
      partitions: 3
      replicas: 3
      config:
        retention.ms: 86400000
        segment.bytes: 1073741824
  users:
    enabled: true
    name: kgl.dev.myapp.users
    spec:
      partitions: 3
      replicas: 3
      config:
        retention.ms: 86400000
        segment.bytes: 1073741824
  products:
    enabled: false
    name: kgl.dev.myapp.products
    spec:
      partitions: 3
      replicas: 3
      config:
        retention.ms: 86400000
        segment.bytes: 1073741824
